### ISSUE TITLE
Navdeep Singh To-Do

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/meta#1]
- [ ] Update sttm-desktop to use Webpack
- [ ] Update banidb-converter script to combine transliterations into one column
- [ ] BaniDB v2 (https://github.com/KhalisFoundation/banidb-api/issues/30)
    - [x] Visraams
    - [ ] Translations
    - [ ] Send diff to apps for updates
- [ ] Document BaniDB API
- [ ] Update LL to use BaniDB
- [ ] Update LL to React
- [ ] Deployment process for anvaad-js
- [ ] Deployment process for sttm-chromecast
- [ ] Deployment process for sttm-shortener

**Comment by tarunsingh5** [comment]
vishraams should no longer be blocked btw

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa the converter script is fixed right?

**Comment by navdeepsinghkhalsa** [comment]
@tarunsingh5 We have to run it to verify that it's fixed. I'll add a status to it
